name: Deploy Staging

on:
  workflow_run:
    workflows: ["Build"]
    branches: [staging]
    types:
      - completed

jobs:
  deploy-stg:
    name: Deploy Staging
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: staging
          fetch-depth: 0
