name: Deploy Develop

on:
  workflow_run:
    workflows: ["Build"]
    branches: [develop]
    types:
      - completed

jobs:
  deploy-dev:
    name: Deploy Develop
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: develop
          fetch-depth: 0
